import json, random, re, pathlib
root=pathlib.Path('/mnt/data/v9')
# Build a balanced 1000-question bank: 100 per category + 100 extra math.
facts={
'Ciencia':[
('planeta más cercano al Sol','Mercurio',['Venus','Marte','Júpiter']),('símbolo químico del oro','Au',['Ag','Fe','Cu']),('gas que usan las plantas en la fotosíntesis','Dióxido de carbono',['Oxígeno','Helio','Hidrógeno']),('huesos aproximados de un adulto humano','206',['106','306','406']),('unidad básica de la vida','Célula',['Átomo','Tejido','Órgano']),('fuerza que atrae objetos hacia la Tierra','Gravedad',['Fricción','Magnetismo','Electricidad']),('planeta conocido como el planeta rojo','Marte',['Venus','Júpiter','Neptuno']),('órgano que bombea la sangre','Corazón',['Pulmón','Hígado','Riñón']),('elemento más abundante del universo','Hidrógeno',['Helio','Oxígeno','Carbono']),('instrumento que mide la temperatura','Termómetro',['Barómetro','Anemómetro','Higrómetro']),('órgano principal del sistema nervioso central','Cerebro',['Corazón','Pulmón','Hígado']),('gas más abundante de la atmósfera terrestre','Nitrógeno',['Oxígeno','Argón','Dióxido de carbono']),('velocidad aproximada de la luz en el vacío','300 000 km/s',['30 000 km/s','3 000 km/s','3 000 000 km/s']),('cambio de líquido a gas','Evaporación',['Condensación','Fusión','Solidificación']),('centro de un átomo','Núcleo',['Corteza','Membrana','Electrón']),('vitamina que produce la piel con luz solar','Vitamina D',['Vitamina C','Vitamina B12','Vitamina K']),('órgano que filtra la sangre y produce orina','Riñón',['Pulmón','Estómago','Corazón']),('satélite natural de la Tierra','Luna',['Fobos','Europa','Titán']),('estrella del sistema solar','Sol',['Sirius','Vega','Polaris']),('escala usada para medir la acidez','pH',['Kelvin','Richter','Celsius']),('mamífero más grande','Ballena azul',['Elefante africano','Jirafa','Orca']),('proceso por el que las plantas producen alimento','Fotosíntesis',['Respiración','Digestión','Fermentación']),('metal líquido a temperatura ambiente','Mercurio',['Hierro','Cobre','Aluminio']),('partícula con carga negativa','Electrón',['Protón','Neutrón','Núcleo']),('ciencia que estudia los seres vivos','Biología',['Geología','Astronomía','Física'])],
'Historia':[
('año del inicio de la Independencia de México','1810',['1821','1910','1808']),('Padre de la Patria en México','Miguel Hidalgo',['Benito Juárez','Porfirio Díaz','Agustín de Iturbide']),('año del fin de la Segunda Guerra Mundial','1945',['1943','1944','1946']),('civilización que construyó Machu Picchu','Inca',['Maya','Azteca','Olmeca']),('primer presidente de Estados Unidos','George Washington',['Abraham Lincoln','Thomas Jefferson','John Adams']),('documento inglés de 1215','Carta Magna',['Tratado de Versalles','Edicto de Milán','Código Napoleónico']),('ciudad sepultada por el Vesubio en el año 79','Pompeya',['Atenas','Esparta','Cartago']),('conquistador español del Imperio mexica','Hernán Cortés',['Francisco Pizarro','Cristóbal Colón','Pedro de Alvarado']),('año de la consumación de la Independencia de México','1821',['1810','1910','1847']),('emperador francés derrotado en Waterloo','Napoleón Bonaparte',['Luis XIV','Carlomagno','Julio César']),('civilización que construyó Chichén Itzá','Maya',['Inca','Romana','Egipcia']),('muro que cayó en 1989','Muro de Berlín',['Muro de Adriano','Gran Muralla','Muro de los Lamentos']),('primer ser humano en llegar a la Luna','Neil Armstrong',['Yuri Gagarin','Buzz Aldrin','John Glenn']),('año del inicio de la Revolución Francesa','1789',['1776','1812','1848']),('antigua ciudad que fue centro del Imperio romano','Roma',['París','Atenas','Londres']),('civilización del antiguo Egipto usaba escritura','Jeroglífica',['Cuneiforme','Latina','Rúnica']),('tratado que puso fin a la Primera Guerra Mundial','Tratado de Versalles',['Tratado de Utrecht','Tratado de Tordesillas','Tratado de París']),('líder de la independencia de India','Mahatma Gandhi',['Nelson Mandela','Sun Yat-sen','Ho Chi Minh']),('año de la llegada de Colón a América','1492',['1453','1519','1607']),('capital del Imperio azteca','Tenochtitlan',['Texcoco','Tlaxcala','Cholula']),('presidente mexicano de la Reforma','Benito Juárez',['Lázaro Cárdenas','Vicente Guerrero','Francisco I. Madero']),('año de la caída del Imperio romano de Occidente','476',['410','395','565']),('inventor asociado a la imprenta de tipos móviles europea','Johannes Gutenberg',['Galileo Galilei','Isaac Newton','Leonardo da Vinci']),('reina egipcia famosa de la dinastía ptolemaica','Cleopatra',['Nefertiti','Hatshepsut','Isis']),('guerra civil estadounidense terminó en','1865',['1850','1877','1890'])],
'Geografía':[
('océano más grande del planeta','Pacífico',['Atlántico','Índico','Ártico']),('capital de Francia','París',['Madrid','Roma','Berlín']),('continente donde está Egipto','África',['Asia','Europa','Oceanía']),('río más largo de Sudamérica','Amazonas',['Paraná','Orinoco','Magdalena']),('capital de Japón','Tokio',['Kioto','Osaka','Hiroshima']),('país con forma aproximada de bota','Italia',['España','Grecia','Portugal']),('desierto cálido más grande','Sahara',['Gobi','Kalahari','Atacama']),('país donde está Cusco','Perú',['Bolivia','Chile','Ecuador']),('montaña más alta sobre el nivel del mar','Everest',['K2','Aconcagua','Kilimanjaro']),('capital de México','Ciudad de México',['Guadalajara','Monterrey','Puebla']),('continente más grande','Asia',['África','Europa','América']),('país con mayor superficie','Rusia',['Canadá','China','Estados Unidos']),('océano entre África y Australia','Índico',['Pacífico','Atlántico','Ártico']),('línea que divide aproximadamente los hemisferios norte y sur','Ecuador',['Trópico de Cáncer','Meridiano de Greenwich','Trópico de Capricornio']),('capital de Argentina','Buenos Aires',['Córdoba','Rosario','Mendoza']),('país donde se encuentra el río Nilo principalmente','Egipto',['Marruecos','Nigeria','Kenia']),('isla más grande del mundo','Groenlandia',['Madagascar','Borneo','Nueva Guinea']),('capital de Canadá','Ottawa',['Toronto','Vancouver','Montreal']),('país donde se encuentra el monte Fuji','Japón',['China','Corea del Sur','Tailandia']),('mar entre Europa y África','Mediterráneo',['Caribe','Báltico','Rojo']),('capital de Australia','Canberra',['Sídney','Melbourne','Perth']),('cordillera que atraviesa gran parte de Sudamérica','Andes',['Alpes','Himalaya','Rocosas']),('país conocido por sus fiordos','Noruega',['Portugal','Egipto','Mongolia']),('capital de Brasil','Brasilia',['Río de Janeiro','São Paulo','Salvador']),('continente donde está el desierto del Sahara','África',['Asia','Europa','Oceanía'])],
'Artistas':[
('pintor de La Mona Lisa','Leonardo da Vinci',['Vincent van Gogh','Pablo Picasso','Claude Monet']),('pintor de Guernica','Pablo Picasso',['Salvador Dalí','Diego Rivera','Goya']),('muralista mexicano esposo de Frida Kahlo','Diego Rivera',['David Alfaro Siqueiros','José Clemente Orozco','Rufino Tamayo']),('compositor de la Novena Sinfonía','Beethoven',['Mozart','Bach','Vivaldi']),('pintor de La noche estrellada','Vincent van Gogh',['Claude Monet','Rembrandt','Edvard Munch']),('escultor de El pensador','Auguste Rodin',['Miguel Ángel','Donatello','Bernini']),('pintora mexicana de Las dos Fridas','Frida Kahlo',['Remedios Varo','Leonora Carrington','María Izquierdo']),('pintor de La persistencia de la memoria','Salvador Dalí',['Picasso','Monet','Velázquez']),('pintor de Impresión, sol naciente','Claude Monet',['Manet','Renoir','Degas']),('escultor del David renacentista','Miguel Ángel',['Rodin','Bernini','Donatello']),('autor de Las meninas','Diego Velázquez',['Goya','El Greco','Murillo']),('pintor de El grito','Edvard Munch',['Monet','Dalí','Klimt']),('compositor de Las cuatro estaciones','Antonio Vivaldi',['Bach','Handel','Chopin']),('compositor de El lago de los cisnes','Chaikovski',['Beethoven','Mozart','Verdi']),('pintor de Los girasoles','Vincent van Gogh',['Picasso','Dalí','Rembrandt']),('artista mexicano conocido por el muralismo y La marcha de la humanidad','David Alfaro Siqueiros',['Diego Rivera','Tamayo','Orozco']),('pintor mexicano de La trinchera','José Clemente Orozco',['Diego Rivera','Siqueiros','Tamayo']),('pintor de La creación de Adán','Miguel Ángel',['Rafael','Leonardo','Caravaggio']),('autor de La escuela de Atenas','Rafael',['Tiziano','Botticelli','Leonardo']),('pintor de El nacimiento de Venus','Sandro Botticelli',['Rafael','Caravaggio','Tiziano']),('compositor de la ópera La flauta mágica','Wolfgang Amadeus Mozart',['Beethoven','Verdi','Wagner']),('compositor de la Novena Sinfonía en re menor','Ludwig van Beethoven',['Brahms','Haydn','Schubert']),('pintor de El beso','Gustav Klimt',['Munch','Monet','Kandinsky']),('artista de las esculturas móviles','Alexander Calder',['Andy Warhol','Banksy','Keith Haring']),('artista asociado al pop art y las latas Campbell','Andy Warhol',['Roy Lichtenstein','Banksy','Basquiat'])],
'Deportes':[
('jugadores de un equipo de fútbol en el campo','11',['9','10','12']),('deporte del aro y balón naranja','Baloncesto',['Tenis','Béisbol','Rugby']),('sets para ganar un Grand Slam masculino normalmente','3',['1','2','4']),('país con más Copas del Mundo masculinas de fútbol','Brasil',['Argentina','Alemania','Francia']),('prueba deportiva de 42.195 km','Maratón',['Sprint','Triatlón','Ciclismo']),('objeto golpeado con un bate en béisbol','Pelota',['Disco','Volante','Balón ovalado']),('deporte con raqueta y volante','Bádminton',['Tenis','Squash','Pádel']),('deporte que usa una portería y un disco','Hockey sobre hielo',['Rugby','Balonmano','Voleibol']),('duración reglamentaria de un partido de fútbol','90 minutos',['60','75','120']),('país sede de los Juegos Olímpicos antiguos','Grecia',['Italia','Egipto','China']),('deporte de Michael Phelps','Natación',['Atletismo','Ciclismo','Remo']),('deporte de Usain Bolt','Atletismo',['Natación','Boxeo','Gimnasia']),('pieza que se mueve en forma de L en ajedrez','Caballo',['Alfil','Torre','Rey']),('cantidad de anillos olímpicos','5',['4','6','7']),('deporte donde se marca un touchdown','Fútbol americano',['Béisbol','Hockey','Críquet']),('deporte donde se usa un scrum','Rugby',['Tenis','Golf','Natación']),('distancia oficial de un maratón','42.195 km',['21.097 km','50 km','10 km']),('deporte con birdie y eagle','Golf',['Béisbol','Hockey','Boxeo']),('deporte donde se disputa Wimbledon','Tenis',['Golf','Críquet','Rugby']),('color de la tarjeta que indica expulsión en fútbol','Roja',['Amarilla','Azul','Verde']),('cantidad de bases en béisbol','4',['3','5','6']),('deporte con clavados desde trampolín','Natación',['Esgrima','Ciclismo','Atletismo']),('país asociado al sumo','Japón',['China','Corea del Sur','Mongolia']),('deporte de contacto con guantes y ring','Boxeo',['Esgrima','Judo','Golf']),('deporte donde se busca hacer jaque mate','Ajedrez',['Damas','Póker','Go'])],
'Literatura':[
('autor de Don Quijote de la Mancha','Miguel de Cervantes',['Gabriel García Márquez','Jorge Luis Borges','Pablo Neruda']),('autor de Cien años de soledad','Gabriel García Márquez',['Mario Vargas Llosa','Julio Cortázar','Octavio Paz']),('género de Romeo y Julieta','Tragedia',['Ensayo','Biografía','Diccionario']),('autor de La Odisea','Homero',['Dante','Virgilio','Sófocles']),('autor de Hamlet','William Shakespeare',['Cervantes','Goethe','Dante']),('autor de La Divina Comedia','Dante Alighieri',['Homero','Virgilio','Boccaccio']),('autor de El principito','Antoine de Saint-Exupéry',['Julio Verne','Victor Hugo','Albert Camus']),('autor de 1984','George Orwell',['Aldous Huxley','Ray Bradbury','J. R. R. Tolkien']),('autor de Orgullo y prejuicio','Jane Austen',['Emily Brontë','Virginia Woolf','Mary Shelley']),('autor de Frankenstein','Mary Shelley',['Jane Austen','Louisa May Alcott','Virginia Woolf']),('autor de La metamorfosis','Franz Kafka',['Thomas Mann','Hermann Hesse','Stefan Zweig']),('autor de El amor en los tiempos del cólera','Gabriel García Márquez',['Mario Benedetti','Pablo Neruda','Carlos Fuentes']),('poeta chileno ganador del Nobel','Pablo Neruda',['Gabriela Mistral','Octavio Paz','Rubén Darío']),('autor de Ficciones','Jorge Luis Borges',['Borges no es autor','Cortázar','Neruda']),('autor de Rayuela','Julio Cortázar',['Borges','Vargas Llosa','Fuentes']),('autor de La ciudad y los perros','Mario Vargas Llosa',['García Márquez','Cortázar','Borges']),('autor de Pedro Páramo','Juan Rulfo',['Carlos Fuentes','Octavio Paz','Juan José Arreola']),('autor de El laberinto de la soledad','Octavio Paz',['Juan Rulfo','Carlos Fuentes','Pablo Neruda']),('autor de Los miserables','Victor Hugo',['Émile Zola','Flaubert','Balzac']),('autor de Madame Bovary','Gustave Flaubert',['Victor Hugo','Zola','Dumas']),('autor de La Ilíada','Homero',['Virgilio','Sófocles','Eurípides']),('autor de Fausto','Johann Wolfgang von Goethe',['Schiller','Dante','Kafka']),('autor de El viejo y el mar','Ernest Hemingway',['Fitzgerald','Steinbeck','Faulkner']),('autor de Moby-Dick','Herman Melville',['Mark Twain','Hemingway','Poe']),('autor de Las aventuras de Tom Sawyer','Mark Twain',['Hemingway','Melville','Poe'])],
'Tecnología':[
('significado de CPU','Unidad Central de Procesamiento',['Control Principal Universal','Código de Procesamiento Único','Unidad de Programa Central']),('sistema usado para gestionar archivos y programas','Sistema operativo',['Navegador','Router','Monitor']),('lenguaje usado para estructurar páginas web','HTML',['CSS','SQL','Python']),('lenguaje usado para dar estilo a páginas web','CSS',['HTML','SQL','C++']),('lenguaje de programación conocido por su uso en ciencia de datos','Python',['HTML','CSS','XML']),('dispositivo que dirige tráfico entre redes','Router',['Monitor','Teclado','Escáner']),('memoria temporal de acceso rápido','RAM',['ROM','SSD','GPU']),('unidad de procesamiento gráfico','GPU',['CPU','RAM','PSU']),('protocolo seguro para navegar por la web','HTTPS',['FTP','HTTP','SMTP']),('tecnología de conexión inalámbrica de corto alcance','Bluetooth',['Ethernet','HDMI','USB']),('servicio que traduce nombres de dominio a direcciones IP','DNS',['HTML','CPU','GPU']),('dispositivo que almacena datos mediante memoria flash','SSD',['RAM','CPU','GPU']),('tecnología para pagos acercando un dispositivo','NFC',['GPS','HDMI','VGA']),('empresa creadora de Android','Google',['Nintendo','IBM','Nokia']),('empresa creadora de Windows','Microsoft',['Apple','Sony','Adobe']),('empresa creadora de macOS','Apple',['Microsoft','Google','IBM']),('red global que conecta millones de dispositivos','Internet',['Intranet','Bluetooth','LAN']),('unidad básica de información digital','Bit',['Byte','Pixel','Hertz']),('ocho bits equivalen a','Un byte',['Un kilobyte','Un nibble','Un megabyte']),('sistema que permite identificar una página web con un nombre','Dominio',['Pixel','Puerto','Proceso']),('tecnología que posiciona mediante satélites','GPS',['NFC','USB','DNS']),('conexión por cable común para periféricos','USB',['GPS','NFC','DNS']),('formato común de imagen con compresión con pérdida','JPEG',['TXT','CSV','WAV']),('formato de audio sin compresión habitual en sistemas','WAV',['PNG','HTML','CSV']),('código que suele ejecutarse en el navegador para interactividad','JavaScript',['SQL','C','Bash'])],
'Cultura':[
('celebración mexicana del 1 y 2 de noviembre','Día de Muertos',['Carnaval','Pascua','Hanami']),('instrumento tradicional mexicano de seis cuerdas','Guitarra',['Arpa celta','Sitar','Oboe']),('danza nacional de Argentina ampliamente reconocida','Tango',['Samba','Flamenco','Haka']),('bebida tradicional mexicana hecha de agave','Pulque',['Sake','Mate','Té verde']),('arte de doblar papel originario de Japón','Origami',['Ikebana','Kabuki','Haiku']),('poema japonés breve tradicional','Haiku',['Soneto','Romance','Oda']),('teatro tradicional japonés con maquillaje y máscaras','Kabuki',['Tango','Flamenco','Ópera']),('arte japonés de arreglar flores','Ikebana',['Origami','Kabuki','Bonsái']),('festival indio conocido como festival de los colores','Holi',['Diwali','Oktoberfest','Hanami']),('festival hindú de las luces','Diwali',['Holi','Hanami','Carnaval']),('tradición española de correr delante de toros','Encierro',['Samba','Oktoberfest','Haka']),('danza brasileña asociada al carnaval','Samba',['Tango','Flamenco','Haka']),('danza española tradicional','Flamenco',['Samba','Tango','Haka']),('bebida argentina y uruguaya de yerba mate','Mate',['Sake','Pulque','Chicha']),('celebración japonesa de contemplar flores de cerezo','Hanami',['Holi','Diwali','Carnaval']),('género musical nacido en Nueva Orleans','Jazz',['Tango','Flamenco','Reggae']),('género musical jamaicano','Reggae',['Jazz','Tango','Fado']),('música tradicional portuguesa asociada a Lisboa','Fado',['Samba','Reggae','Tango']),('comida japonesa de arroz avinagrado','Sushi',['Paella','Ceviche','Taco']),('comida española de arroz','Paella',['Sushi','Taco','Ceviche']),('platillo peruano de pescado marinado en cítricos','Ceviche',['Paella','Sushi','Taco']),('platillo mexicano de tortilla y relleno','Taco',['Sushi','Paella','Ceviche']),('arte marcial japonés de agarres y proyecciones','Judo',['Karate','Taekwondo','Capoeira']),('arte marcial coreano conocido por sus patadas','Taekwondo',['Judo','Karate','Capoeira']),('arte marcial brasileño que combina lucha y música','Capoeira',['Judo','Karate','Taekwondo'])],
'Matemáticas':[]
}
# Create 100 variants per non-math fact pool, then 100 extra math from existing verified questions.
variants=[
 lambda s,a:f'¿Cuál es {s}?',
 lambda s,a:f'En conocimientos generales, ¿cuál corresponde a {s}?',
 lambda s,a:f'¿Qué opción identifica correctamente {s}?',
 lambda s,a:f'Si te preguntan por {s}, ¿qué respuesta elegirías?'
]
qs=[]; qid=1
for cat, pool in facts.items():
    if cat=='Matemáticas': continue
    for idx,(stem,ans,dists) in enumerate(pool):
        for vi,vf in enumerate(variants):
            opts=[ans]+dists
            # rotate distractors deterministically to vary placement
            shift=(idx+vi)%4
            opts=opts[shift:]+opts[:shift]
            qs.append({'id':qid,'category':cat,'question':vf(stem,ans),'options':opts,'answer':opts.index(ans),'explanation':f'La respuesta correcta es {ans}.'})
            qid+=1
# Existing math questions, keep first 100 and then add 100 more distinct-ish by using later entries.
old=json.load(open(root/'questions.json',encoding='utf8'))
math=[q for q in old if q.get('category')=='Matemáticas']
# use 200 math questions, preferring unique question strings
seen=set()
for q in math:
    if q['question'] in seen: continue
    seen.add(q['question'])
    nq=dict(q); nq['id']=qid; qs.append(nq); qid+=1
    if len([x for x in qs if x['category']=='Matemáticas'])>=100: break
# Need 1000 exactly: currently 8*100 +100 math =900; add 100 extra math from remaining
for q in math:
    if q['question'] in seen: continue
    seen.add(q['question']); nq=dict(q); nq['id']=qid; qs.append(nq); qid+=1
    if len([x for x in qs if x['category']=='Matemáticas'])>=200: break
# If still short, create arithmetic questions until 1000.
while len(qs)<1000:
    i=len(qs)+1; a=(i*7)%90+10; b=(i*11)%50+1; ans=a+b
    opts=[str(ans),str(ans+10),str(ans-10),str(a*b)]
    qs.append({'id':qid,'category':'Matemáticas','question':f'¿Cuál es el resultado de {a} + {b}?','options':opts,'answer':0,'explanation':f'{a} + {b} = {ans}.'}); qid+=1
# Re-number and shuffle globally.
for i,q in enumerate(qs,1): q['id']=i
random.seed(20260828); random.shuffle(qs)
# Save JSON and JS immediate bank
json.dump(qs,open(root/'questions.json','w',encoding='utf8'),ensure_ascii=False,indent=2)
open(root/'questions-data.js','w',encoding='utf8').write('window.QUESTION_BANK='+json.dumps(qs,ensure_ascii=False,separators=(',',':'))+';')
from collections import Counter
print(len(qs),Counter(q['category'] for q in qs))
